# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    serializer:
        enabled: true
        enable_attributes: true
        mapping:
            paths: ['%kernel.project_dir%/src/Entity']

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
