<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKBXaeEL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKBXaeEL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKBXaeEL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKBXaeEL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKBXaeEL\App_KernelDevDebugContainer([
    'container.build_hash' => 'KBXaeEL',
    'container.build_id' => '948879b8',
    'container.build_time' => 1746624369,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKBXaeEL');
