<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'create_checkout_session' => [[], ['_controller' => 'App\\Controller\\PaymentController::createCheckoutSession'], [], [['text', '/api/checkout']], [], [], []],
    'stripe_webhook' => [[], ['_controller' => 'App\\Controller\\PaymentController::stripeWebhook'], [], [['text', '/api/webhook']], [], [], []],
    'payment_success' => [['orderId'], ['_controller' => 'App\\Controller\\PaymentController::paymentSuccess'], [], [['variable', '/', '[^/]++', 'orderId', true], ['text', '/api/payment/success']], [], [], []],
    'payment_cancel' => [['orderId'], ['_controller' => 'App\\Controller\\PaymentController::paymentCancel'], [], [['variable', '/', '[^/]++', 'orderId', true], ['text', '/api/payment/cancel']], [], [], []],
    'product_list' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/api/products']], [], [], []],
    'product_show' => [['id'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
    'product_create' => [[], ['_controller' => 'App\\Controller\\ProductController::create'], [], [['text', '/api/products']], [], [], []],
    'product_update' => [['id'], ['_controller' => 'App\\Controller\\ProductController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
    'product_delete' => [['id'], ['_controller' => 'App\\Controller\\ProductController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
    'App\Controller\PaymentController::createCheckoutSession' => [[], ['_controller' => 'App\\Controller\\PaymentController::createCheckoutSession'], [], [['text', '/api/checkout']], [], [], []],
    'App\Controller\PaymentController::stripeWebhook' => [[], ['_controller' => 'App\\Controller\\PaymentController::stripeWebhook'], [], [['text', '/api/webhook']], [], [], []],
    'App\Controller\PaymentController::paymentSuccess' => [['orderId'], ['_controller' => 'App\\Controller\\PaymentController::paymentSuccess'], [], [['variable', '/', '[^/]++', 'orderId', true], ['text', '/api/payment/success']], [], [], []],
    'App\Controller\PaymentController::paymentCancel' => [['orderId'], ['_controller' => 'App\\Controller\\PaymentController::paymentCancel'], [], [['variable', '/', '[^/]++', 'orderId', true], ['text', '/api/payment/cancel']], [], [], []],
    'App\Controller\ProductController::index' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/api/products']], [], [], []],
    'App\Controller\ProductController::show' => [['id'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
    'App\Controller\ProductController::create' => [[], ['_controller' => 'App\\Controller\\ProductController::create'], [], [['text', '/api/products']], [], [], []],
    'App\Controller\ProductController::update' => [['id'], ['_controller' => 'App\\Controller\\ProductController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
    'App\Controller\ProductController::delete' => [['id'], ['_controller' => 'App\\Controller\\ProductController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/products']], [], [], []],
];
